Repository anupam-kumar-krishnan/Competitive_Programming, pull requests merged in 2021-10, with the labels that each got.

#6 Added MedianRowWiseSorted.cpp
  DSA 450/Matrix/MedianRowWiseSorted.cpp
  DSA 450/Matrix/MedianRowWiseSorted.exe
Labels: hacktoberfest-accepted

#9 Create Maximize the Confusion of an Exam.java
  LeetCode/Maximize the Confusion of an Exam.java
Labels: hacktoberfest-accepted

#12 Problem Code: PROBDIFF Added
  CodeChef/Practice/PROBDIFF.cpp
Labels: hacktoberfest-accepted

#14 Added code to Travel Pass Problem | Codechef
  CodeChef/September 2021 Long Challenge/Travel Pass/readme.md
  CodeChef/September 2021 Long Challenge/Travel Pass/travel_pass.cpp
Labels: hacktoberfest-accepted

#15 Linear Search Algorithm - searching(CPP)
  Linear Search.cpp
Labels: hacktoberfest-accepted

#19 added firstRepeated.cpp
  DSA 450/String/FirstRepeated.cpp
Labels: hacktoberfest-accepted

#20 Add files via upload
  CodeChef/Practice/Food Chain.cpp
Labels: hacktoberfest-accepted

#21 XOR EQUAL
  CodeChef/September 2021 Long Challenge/xor equal.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#24 RangeSumBST.java
  LeetCode/RangeSumBST.java
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#25 Insert_Into_BST( Leetcode - 701 )
  LeetCode/Insert_Into_BST.java
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#27 FILL GRID
  grid.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#26 Create tictacgame .cpp
  tictacgame .cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#28 Create trie.cpp
  trie.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#29 Create TrappingRainWater.cpp
  Arrays/TrappingRainWater.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#32 Create LIS.cpp
  LIS.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#31 Create Final Value of Variable After Performing Operations.cpp
  LeetCode/Final Value of Variable After Performing Operations.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#30 POSITIVE SPEWING
  spewing.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#33 Create LCS.cpp
  LeetCode/LCS.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#34 Add files via upload
  Heap_sort.cpp
  Max_heap.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#35 Friends
  Arrays/A chess game.cpp
  Friends.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#38 Checking a number is palindrome or not
  Basic Programming/Checking palindrome.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#37 Increase input flexibility
  CodeChef/Practice/Chief_in_Vaccination_Queue.cpp
  CodeChef/Practice/Magical_Doors.cpp
  CodeChef/Practice/Maximum_Light_Up.cpp
  CodeChef/Practice/The_Preparations.cpp
  Linear Search.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#36 Binary
  A chess game.cpp
  Binary.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#39 Please add to Array Problems
  Print matrix in spiral order.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#40 Search and Sort algorithm code c++
  search_algorithum_code/binary_search.cpp
  search_algorithum_code/linear_search.cpp
  sorting_algorithm_code/Count_sort/count_sort.cpp
  sorting_algorithm_code/Count_sort/count_sort.exe
  sorting_algorithm_code/DNF_sort/dnf_sort.cpp
  sorting_algorithm_code/DNF_sort/dnf_sort.exe
  sorting_algorithm_code/Quick_sort/Quick_sort.cpp
  sorting_algorithm_code/Quick_sort/Quick_sort.exe
  sorting_algorithm_code/wave_sort/wave_sort.cpp
  sorting_algorithm_code/wave_sort/wave_sort.exe
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#41 Vanya and Lanterns
  Codeforces/Vanya_and_Lanterns.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#42 Sudoku Solver
  LeetCode/sudoku.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#43 Checking a number is prime or not
  Basic Programming/Checking a number is prime or not.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#44 Create TowerOfHanoi.cpp
  TowerOfHanoi.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#46 October Long Challenge 🚀
  CodeChef/October Long Challenge 2021/LongestANDSubarray.cpp
  CodeChef/October Long Challenge 2021/MEX-OR.cpp
  CodeChef/October Long Challenge 2021/Three Boxes.cpp
  CodeChef/October Long Challenge 2021/Which Mixture.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021, CodeChef-long-challenge

#45 Added Graphs, Trees and Sorting Algorithms source code
  GRAPHS/BreadthFirstSearch.cpp
  GRAPHS/DepthFirstSearchUsingSTL.cpp
  GRAPHS/Kruskal'sMinSpanningTree.cpp
  GRAPHS/PrimsMinSpanningTree.cpp
  TREE/AVLTREE.C
  TREE/BST.C
  TREE/BST.cpp
  TREE/DeletionAVL.cpp
  TREE/Tree.c
  TREE/Tree.cpp
  sorting_algorithm_code/BubbleSort.cpp
  sorting_algorithm_code/Bucket-BinSort.cpp
  sorting_algorithm_code/InsertionSort.cpp
  sorting_algorithm_code/IterativeMergeSort.cpp
  sorting_algorithm_code/RadixSort.cpp
  sorting_algorithm_code/RecursiveMergeSort.cpp
  sorting_algorithm_code/SelectionSort.cpp
  sorting_algorithm_code/ShellSort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#49 Add graph algorithms
  bellmanford.cpp
  kruskals.cpp
  prims.cpp
  primsOptimized.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#48 Create Next Round.cpp
  Boy or Girl.cpp
  Next Round.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#50 Create Reverse_stack_using_recursion.cpp
  DSA 450/Stack/Reverse_stack_using_recursion.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#52 Create LeetCode_Reconstruct Original Digits from English.cpp
  LeetCode/Reconstruct Original Digits from English.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#51 Create DishonestSellers.cpp
  Codeforces/DishonestSellers.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#53 Added solution to Leetcode problem number 273
  LeetCode/Integer to English Words.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#55 Sorting algorithms code
  Sorting_algorithm_code/bubble_sort.cpp
  Sorting_algorithm_code/insertion_sort.cpp
  Sorting_algorithm_code/merge_sort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#58 Create Best Time to Buy and Sell Stock.cpp
  LeetCode/Best Time to Buy and Sell Stock.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#57 Update Reverse String.cpp
  DSA 450/String/Reverse String.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#59 Fenwick Tree
  TREE/fenwickTree_countInversion.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#60 saurabh added binary.py for hackoberfest2021
  search_algorithum_code/binary.py
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#288 Add 430. Flatten a Multilevel Doubly Linked List.py
  Coding Platforms(codechef,codeforces,etc)/LeetCode/430. Flatten a Multilevel Doubly Linked List.py
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#287 program for Minimize_the_height
  All Languages/C++ Codes/Minimize_the_height.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#286 Create Rotate_array.py
  All Languages/Python Codes/Rotate_array.py
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#285 RSA ALGORITHM
  All Languages/C++ Codes/A_AB_Balance.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#289 Create 1597B-ShiftingSort.cpp
  Coding Platforms(codechef,codeforces,etc)/Codeforces/1597B-ShiftingSort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2021
